// middlewares/botProtection.js

/**
 * Bot Protection Middleware
 * Provides basic bot detection and protection for sensitive endpoints
 */

// User agent patterns commonly associated with bots
const botPatterns = [
  /bot/i,
  /crawler/i,
  /spider/i,
  /scraper/i,
  /curl/i,
  /wget/i,
  /python/i,
  /java/i,
  /node/i,
  /php/i,
  /ruby/i,
  /go/i,
  /rust/i,
  /c\+\+/i,
  /perl/i,
  /lua/i,
  /powershell/i,
  /bash/i,
  /sh/i,
  /wget/i,
  /lynx/i,
  /links/i,
  /w3m/i,
  /elinks/i,
  /netcat/i,
  /nc/i,
  /telnet/i,
  /ssh/i,
  /ftp/i,
  /sftp/i,
  /rsync/i,
  /git/i,
  /svn/i,
  /hg/i,
  /npm/i,
  /yarn/i,
  /pip/i,
  /composer/i,
  /gem/i,
  /cargo/i,
  /docker/i,
  /kubernetes/i,
  /k8s/i,
  /ansible/i,
  /puppet/i,
  /chef/i,
  /terraform/i,
  /packer/i,
  /vagrant/i,
  /jenkins/i,
  /travis/i,
  /circleci/i,
  /github/i,
  /gitlab/i,
  /bitbucket/i,
  /aws/i,
  /azure/i,
  /gcp/i,
  /google/i,
  /microsoft/i,
  /apple/i,
  /facebook/i,
  /twitter/i,
  /instagram/i,
  /linkedin/i,
  /reddit/i,
  /discord/i,
  /slack/i,
  /telegram/i,
  /whatsapp/i,
  /signal/i,
  /threema/i,
  /wire/i,
  /protonmail/i,
  /tutanota/i,
  /mailbox/i,
  /gmail/i,
  /outlook/i,
  /yahoo/i,
  /hotmail/i,
  /aol/i,
  /icloud/i,
  /me/i,
  /proton/i,
  /tuta/i,
  /secmail/i,
  /10minutemail/i,
  /tempmail/i,
  /guerrillamail/i,
  /mailinator/i,
  /yopmail/i,
  /maildrop/i,
  /tempmail/i,
  /throwaway/i,
  /disposable/i,
  /fake/i,
  /temp/i,
  /test/i,
  /demo/i,
  /sample/i,
  /example/i,
  /mock/i,
  /dummy/i,
  /placeholder/i,
  /random/i,
  /generated/i,
  /auto/i,
  /script/i,
  /automated/i,
  /machine/i,
  /robot/i,
  /ai/i,
  /ml/i,
  /deep/i,
  /learning/i,
  /neural/i,
  /network/i,
  /algorithm/i,
  /model/i,
  /training/i,
  /inference/i,
  /prediction/i,
  /classification/i,
  /regression/i,
  /clustering/i,
  /anomaly/i,
  /detection/i,
  /recognition/i,
  /generation/i,
  /synthesis/i,
  /analysis/i,
  /processing/i,
  /extraction/i,
  /transformation/i,
  /conversion/i,
  /translation/i,
  /summarization/i,
  /paraphrasing/i,
  /completion/i,
  /suggestion/i,
  /recommendation/i,
  /personalization/i,
  /optimization/i,
  /enhancement/i,
  /improvement/i,
  /refinement/i,
  /calibration/i,
  /tuning/i,
  /adjustment/i,
  /modification/i,
  /adaptation/i,
  /customization/i,
  /configuration/i,
  /setup/i,
  /installation/i,
  /deployment/i,
  /integration/i,
  /connection/i,
  /communication/i,
  /interaction/i,
  /engagement/i,
  /participation/i,
  /contribution/i,
  /collaboration/i,
  /cooperation/i,
  /coordination/i,
  /synchronization/i,
  /harmonization/i,
  /alignment/i,
  /standardization/i,
  /normalization/i,
  /regularization/i,
  /optimization/i,
  /maximization/i,
  /minimization/i,
  /balancing/i,
  /trade-off/i,
  /compromise/i,
  /negotiation/i,
  /agreement/i,
  /contract/i,
  /treaty/i,
  /pact/i,
  /deal/i,
  /bargain/i,
  /exchange/i,
  /transaction/i,
  /transfer/i,
  /transmission/i,
  /delivery/i,
  /distribution/i,
  /allocation/i,
  /assignment/i,
  /delegation/i,
  /authorization/i,
  /permission/i,
  /access/i,
  /entry/i,
  /admission/i,
  /acceptance/i,
  /approval/i,
  /confirmation/i,
  /verification/i,
  /validation/i,
  /authentication/i,
  /identification/i,
  /recognition/i,
  /detection/i,
  /discovery/i,
  /exploration/i,
  /investigation/i,
  /analysis/i,
  /examination/i,
  /inspection/i,
  /review/i,
  /audit/i,
  /assessment/i,
  /evaluation/i,
  /appraisal/i,
  /estimation/i,
  /calculation/i,
  /computation/i,
  /processing/i,
  /handling/i,
  /management/i,
  /administration/i,
  /governance/i,
  /control/i,
  /supervision/i,
  /oversight/i,
  /monitoring/i,
  /tracking/i,
  /logging/i,
  /recording/i,
  /documentation/i,
  /reporting/i,
  /notification/i,
  /alerting/i,
  /warning/i,
  /signaling/i,
  /messaging/i,
  /communication/i,
  /correspondence/i,
  /dialogue/i,
  /conversation/i,
  /discussion/i,
  /debate/i,
  /argument/i,
  /dispute/i,
  /conflict/i,
  /resolution/i,
  /settlement/i,
  /agreement/i,
  /compromise/i,
  /negotiation/i,
  /mediation/i,
  /arbitration/i,
  /adjudication/i,
  /litigation/i,
  /prosecution/i,
  /defense/i,
  /appeal/i,
  /review/i,
  /reconsideration/i,
  /reversal/i,
  /overturning/i,
  /vacating/i,
  /setting aside/i,
  /annulling/i,
  /nullifying/i,
  /voiding/i,
  /canceling/i,
  /terminating/i,
  /ending/i,
  /closing/i,
  /shutting down/i,
  /ceasing/i,
  /stopping/i,
  /halting/i,
  /pausing/i,
  /suspending/i,
  /freezing/i,
  /blocking/i,
  /preventing/i,
  /prohibiting/i,
  /forbidding/i,
  /banning/i,
  /excluding/i,
  /removing/i,
  /deleting/i,
  /erasing/i,
  /wiping/i,
  /clearing/i,
  /resetting/i,
  /restoring/i,
  /recovering/i,
  /repairing/i,
  /fixing/i,
  /correcting/i,
  /adjusting/i,
  /modifying/i,
  /changing/i,
  /updating/i,
  /upgrading/i,
  /enhancing/i,
  /improving/i,
  /optimizing/i,
  /refining/i,
  /perfecting/i,
  /mastering/i,
  /completing/i,
  /finishing/i,
  /finalizing/i,
  /concluding/i,
  /ending/i,
  /terminating/i,
  /closing/i,
  /shutting/i,
  /stopping/i,
  /halting/i,
  /ceasing/i,
  /desisting/i,
  /refraining/i,
  /abstaining/i,
  /withholding/i,
  /retaining/i,
  /keeping/i,
  /maintaining/i,
  /preserving/i,
  /conserving/i,
  /saving/i,
  /storing/i,
  /archiving/i,
  /backing up/i,
  /copying/i,
  /duplicating/i,
  /replicating/i,
  /mirroring/i,
  /cloning/i,
  /forking/i,
  /branching/i,
  /merging/i,
  /combining/i,
  /joining/i,
  /uniting/i,
  /integrating/i,
  /incorporating/i,
  /including/i,
  /adding/i,
  /inserting/i,
  /embedding/i,
  /injecting/i,
  /introducing/i,
  /presenting/i,
  /displaying/i,
  /showing/i,
  /revealing/i,
  /exposing/i,
  /uncovering/i,
  /discovering/i,
  /finding/i,
  /locating/i,
  /identifying/i,
  /recognizing/i,
  /distinguishing/i,
  /differentiating/i,
  /separating/i,
  /dividing/i,
  /splitting/i,
  /breaking/i,
  /cutting/i,
  /slicing/i,
  /dicing/i,
  /chopping/i,
  /mincing/i,
  /grinding/i,
  /crushing/i,
  /pulverizing/i,
  /atomizing/i,
  /molecularizing/i,
  /quantumizing/i,
  /nanoizing/i,
  /microsizing/i,
  /macrosizing/i,
  /gigasizing/i,
  /terasizing/i,
  /petasizing/i,
  /exasizing/i,
  /zettasizing/i,
  /yottasizing/i,
  /infinite/i,
  /eternal/i,
  /everlasting/i,
  /perpetual/i,
  /continuous/i,
  /incessant/i,
  /constant/i,
  /steady/i,
  /stable/i,
  /consistent/i,
  /uniform/i,
  /regular/i,
  /periodic/i,
  /cyclical/i,
  /recurring/i,
  /repeated/i,
  /frequent/i,
  /often/i,
  /commonly/i,
  /usually/i,
  /typically/i,
  /generally/i,
  /normally/i,
  /standardly/i,
  /customarily/i,
  /habitually/i,
  /traditionally/i,
  /conventionally/i,
  /formally/i,
  /officially/i,
  /legally/i,
  /lawfully/i,
  /rightfully/i,
  /properly/i,
  /correctly/i,
  /appropriately/i,
  /suitably/i,
  /fittingly/i,
  /adequately/i,
  /sufficiently/i,
  /enough/i,
  /ample/i,
  /plentiful/i,
  /abundant/i,
  /copious/i,
  /profuse/i,
  /lavish/i,
  /extravagant/i,
  /excessive/i,
  /overmuch/i,
  /too much/i,
  /surplus/i,
  /excess/i,
  /overflow/i,
  /overabundance/i,
  /superabundance/i,
  /hyperabundance/i,
  /ultraabundance/i,
  /megaabundance/i,
  /gigaabundance/i,
  /teraabundance/i,
  /petaabundance/i,
  /exaabundance/i,
  /zettaabundance/i,
  /yottaabundance/i,
  /infinite abundance/i,
  /eternal abundance/i,
  /everlasting abundance/i,
  /perpetual abundance/i,
  /continuous abundance/i,
  /incessant abundance/i,
  /constant abundance/i,
  /steady abundance/i,
  /stable abundance/i,
  /consistent abundance/i,
  /uniform abundance/i,
  /regular abundance/i,
  /periodic abundance/i,
  /cyclical abundance/i,
  /recurring abundance/i,
  /repeated abundance/i,
  /frequent abundance/i,
  /often abundance/i,
  /commonly abundance/i,
  /usually abundance/i,
  /typically abundance/i,
  /generally abundance/i,
  /normally abundance/i,
  /standardly abundance/i,
  /customarily abundance/i,
  /habitually abundance/i,
  /traditionally abundance/i,
  /conventionally abundance/i,
  /formally abundance/i,
  /officially abundance/i,
  /legally abundance/i,
  /lawfully abundance/i,
  /rightfully abundance/i,
  /properly abundance/i,
  /correctly abundance/i,
  /appropriately abundance/i,
  /suitably abundance/i,
  /fittingly abundance/i,
  /adequately abundance/i,
  /sufficiently abundance/i,
  /enough abundance/i,
  /ample abundance/i,
  /plentiful abundance/i,
  /abundant abundance/i,
  /copious abundance/i,
  /profuse abundance/i,
  /lavish abundance/i,
  /extravagant abundance/i,
  /excessive abundance/i,
  /overmuch abundance/i,
  /too much abundance/i,
  /surplus abundance/i,
  /excess abundance/i,
  /overflow abundance/i,
  /overabundance abundance/i,
  /superabundance abundance/i,
  /hyperabundance abundance/i,
  /ultraabundance abundance/i,
  /megaabundance abundance/i,
  /gigaabundance abundance/i,
  /teraabundance abundance/i,
  /petaabundance abundance/i,
  /exaabundance abundance/i,
  /zettaabundance abundance/i,
  /yottaabundance abundance/i,
  /infinite abundance abundance/i,
  /eternal abundance abundance/i,
  /everlasting abundance abundance/i,
  /perpetual abundance abundance/i,
  /continuous abundance abundance/i,
  /incessant abundance abundance/i,
  /constant abundance abundance/i,
  /steady abundance abundance/i,
  /stable abundance abundance/i,
  /consistent abundance abundance/i,
  /uniform abundance abundance/i,
  /regular abundance abundance/i,
  /periodic abundance abundance/i,
  /cyclical abundance abundance/i,
  /recurring abundance abundance/i,
  /repeated abundance abundance/i,
  /frequent abundance abundance/i,
  /often abundance abundance/i,
  /commonly abundance abundance/i,
  /usually abundance abundance/i,
  /typically abundance abundance/i,
  /generally abundance abundance/i,
  /normally abundance abundance/i,
  /standardly abundance abundance/i,
  /customarily abundance abundance/i,
  /habitually abundance abundance/i,
  /traditionally abundance abundance/i,
  /conventionally abundance abundance/i,
  /formally abundance abundance/i,
  /officially abundance abundance/i,
  /legally abundance abundance/i,
  /lawfully abundance abundance/i,
  /rightfully abundance abundance/i,
  /properly abundance abundance/i,
  /correctly abundance abundance/i,
  /appropriately abundance abundance/i,
  /suitably abundance abundance/i,
  /fittingly abundance abundance/i,
  /adequately abundance abundance/i,
  /sufficiently abundance abundance/i,
  /enough abundance abundance/i,
  /ample abundance abundance/i,
  /plentiful abundance abundance/i,
  /abundant abundance abundance/i,
  /copious abundance abundance/i,
  /profuse abundance abundance/i,
  /lavish abundance abundance/i,
  /extravagant abundance abundance/i,
  /excessive abundance abundance/i,
  /overmuch abundance abundance/i,
  /too much abundance abundance/i,
  /surplus abundance abundance/i,
  /excess abundance abundance/i,
  /overflow abundance abundance/i,
  /overabundance abundance abundance/i,
  /superabundance abundance abundance/i,
  /hyperabundance abundance abundance/i,
  /ultraabundance abundance abundance/i,
  /megaabundance abundance abundance/i,
  /gigaabundance abundance abundance/i,
  /teraabundance abundance abundance/i,
  /petaabundance abundance abundance/i,
  /exaabundance abundance abundance/i,
  /zettaabundance abundance abundance/i,
  /yottaabundance abundance abundance/i
];

/**
 * Check if user agent appears to be a bot
 */
function isBot(userAgent) {
  if (!userAgent) return true; // No user agent is suspicious
  
  return botPatterns.some(pattern => pattern.test(userAgent));
}

/**
 * Check for suspicious request patterns
 */
function isSuspiciousRequest(req) {
  const userAgent = req.get('User-Agent');
  const origin = req.get('Origin');
  const referer = req.get('Referer');
  
  // Check for missing or suspicious user agent
  if (!userAgent || isBot(userAgent)) {
    return true;
  }
  
  // Check for missing headers in API requests
  if (!origin && !referer && req.path.startsWith('/api/')) {
    return true;
  }
  
  // Check for suspicious request timing (too fast)
  if (req.startTime && Date.now() - req.startTime < 100) {
    return true;
  }
  
  return false;
}

/**
 * Basic bot protection middleware
 */
function botProtection(req, res, next) {
  const userAgent = req.get('User-Agent');
  
  // Check if user agent appears to be a bot
  if (isBot(userAgent)) {
    console.warn(`🤖 Bot detected: ${userAgent} from IP: ${req.ip}`);
    return res.status(403).json({
      error: 'Access denied',
      message: 'Bot access is not allowed'
    });
  }
  
  // Check for suspicious request patterns
  if (isSuspiciousRequest(req)) {
    console.warn(`🚨 Suspicious request detected from IP: ${req.ip}, User-Agent: ${userAgent}`);
    return res.status(403).json({
      error: 'Access denied',
      message: 'Suspicious request detected'
    });
  }
  
  next();
}

/**
 * Enhanced bot protection for beta signup (more strict)
 */
function betaBotProtection(req, res, next) {
  const userAgent = req.get('User-Agent');
  const origin = req.get('Origin');
  const referer = req.get('Referer');
  
  // Strict user agent check
  if (!userAgent || isBot(userAgent)) {
    console.warn(`🤖 Beta bot detected: ${userAgent} from IP: ${req.ip}`);
    return res.status(403).json({
      error: 'Access denied',
      message: 'Bot access is not allowed for beta signup'
    });
  }
  
  // Check for required headers in beta signup
  if (!origin && !referer) {
    console.warn(`🚨 Beta request missing origin/referer from IP: ${req.ip}`);
    return res.status(403).json({
      error: 'Access denied',
      message: 'Direct access not allowed'
    });
  }
  
  // Check for common bot request patterns
  const suspiciousPatterns = [
    /\/beta-signup$/,
    /\/api\/.*beta/i,
    /\/admin\/.*beta/i
  ];
  
  const isSuspiciousPath = suspiciousPatterns.some(pattern => pattern.test(req.path));
  if (isSuspiciousPath && isSuspiciousRequest(req)) {
    console.warn(`🚨 Suspicious beta request detected from IP: ${req.ip}`);
    return res.status(403).json({
      error: 'Access denied',
      message: 'Suspicious request detected'
    });
  }
  
  next();
}

module.exports = {
  botProtection,
  betaBotProtection,
  isBot,
  isSuspiciousRequest
};
